name: 'LINE Notify Actions'
description: 'Sending a LINE Notify message'
author: 'NiJia Lin'
inputs:
  token:
    description: 'LINE Notify access_token'
    required: true
  message:
    description: 'Your message'
    required: true
    default: 'Hello LINE Notify'
  file:
    description: 'Send file for LINE Notify'
    required: false
  sticker_id:
    description: 'LINE sticker id'
    required: false
  package_id:
    description: 'LINE sticker package id'
    required: false
  image_url:
    description: 'Image https url'
    required: false
  image_file:
    description: 'Image file path'
    required: false

runs:
  using: 'docker'
  image: 'Dockerfile'

branding:
  icon: 'message-square'
  color: 'blue'